### ISSUE TITLE
artifactory.target missing

### ISSUE THREAD

**Issue by kgoedert** [leedavidr/grunt-artifactory-artifact#33]
Hi,

I just started with grunt, so excuse me if the question is too simple... 
I installed the plugin, and loaded it according to the instructions and added this

```json
artifactory: {
      options: {
        url: 'http://artifactory.google.com:8080',
        repository: 'jslibraries',
        username: 'admin',
        password: 'admin123'
      },
      client: {
        files: [
          { src: ['dist/**/*'] }
        ],
        options: {
          publish: [{
            id: 'com.mycompany.js:built-artifact:tgz',
            version: 'my-version',
            path: 'dist/'
          }],
          parameters: [
            'build.name=built-artifact',
            'version=my-version',
            'vcs.revision=my-revision',
          ]
        }
      }
```
the url I changed to my server. When I run grunt artifactory:target:publish I get this message:

Running "artifactory:target:publish" (artifactory) task
Verifying property artifactory.target exists in config...ERROR
>> Unable to process task.
Warning: Required config property "artifactory.target" missing

Where should I set the property?

Thanks

**Comment by TaylorHG** [comment]
Any resolution to this?

**Comment by leedavidr** [comment]
I forget how this plugin was used, but I believe "target" in the command is "client" in this case
artifactory:client:publish
