### ISSUE TITLE
Accessing Secure URL artifactory

### ISSUE THREAD

**Issue by crazyUI** [leedavidr/grunt-artifactory-artifact#35]
UNABLE_TO_VERIFY_LEAF_SIGNATURE - Getting this error when I try to access a secure artifactory path. Is there any workaround to solve this issue.. 

Thank you!!

**Comment by leedavidr** [comment]
This might have to do with node, seems like a config option
http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature
http://stackoverflow.com/questions/20747817/error-unable-to-verify-leaf-signature-phonegap-installation
