### ISSUE TITLE
Unable to use custom archive name

### ISSUE THREAD

**Issue by rrijnberk** [leedavidr/grunt-artifactory-artifact#36]
As it works now the project name and version are used for both the registry folder and artifact name. This works but does not allow for the use of custom schemes for artifact names.

I.E. uploading an artifact for project **my-project** with version **0.1.0** under **nl.rrijnberk.js** i would end up with the following path everytime:
**artifactory/registry/nl/rrijnberk/js/my-project/0.1.0/my-project-0.1.0.tgz**

Compress supports the archive option for custom archive names. And as a lot of documentation refers to compress i would like to be able to use the archive option.

**Comment by leedavidr** [comment]
Merged pull request, thank you
